development:
  access_key_id: AKIAIVJD3KPZHOA4L5HA
  secret_access_key: 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

production:
  access_key_id: AKIAIVJD3KPZHOA4L5HA
  secret_access_key: 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